### ISSUE TITLE
ERROR in build.js from UglifyJs

### ISSUE THREAD

**Issue by alcnsahin** [ankurk91/vue-toast-notification#56]
Hello,

I am getting the following error while building a Vue.js application. How to fix it?

`ERROR in build.js from UglifyJs
Unexpected token: punc ()) [./node_modules/vue-toast-notification/dist/index.min.js:1,225][build.js:23778,189]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! drmon-frontend@1.0.0 build: cross-env NODE_ENV=production webpack --progress --hide-modules
npm ERR! Exit status 2`

Thanks.

**Comment by ankurk91** [comment]
Hey,

What is your laravel-mix version?
Looks like you are using  quite old version which is using `UglifyJs` rather than [TerserJS](https://github.com/terser/terser)

UglifyJs does not support parsing ES6 syntax.
Upgrade you laravel-mix to v5 or above which is using [TerserJS](https://github.com/terser/terser)
